name:                haskell-yesod-intro

default-extensions:
- OverloadedStrings
- FlexibleInstances
- TypeFamilies

dependencies:
- base >= 4.7 && < 5
- yesod
- monad-logger
- persistent-postgresql
- resource-pool
- aeson

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wno-missing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskell-yesod-intro-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-yesod-intro

tests:
  haskell-yesod-intro-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-yesod-intro
